import type { Metadata } from "next";
import { Inter } from "next/font/google";

import LayoutHeader from "@/components/layout/Header";
import LayoutSidebarRight from "@/components/layout/SidebarRight";
import LayoutSidebarLeft from "@/components/layout/SidebarLeft";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutHeader />
        <div className="max-w-content mx-auto md:flex">
          <LayoutSidebarLeft />
          <main className="grow">{children}</main>
          <LayoutSidebarRight />
        </div>
      </body>
    </html>
  );
}
